### ISSUE TITLE
Need to update for R 3.5.1 onwards

### ISSUE THREAD

**Issue by ishonest** [jaredhuling/rESN#1]
How do I debug this problem?

`> devtools::install_github("jaredhuling/rESN")
Downloading GitHub repo jaredhuling/rESN@master
from URL https://api.github.com/repos/jaredhuling/rESN/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.4)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing rESN
Installing 1 package: Rcpp
Installing package into ‘C:/Users/Sagar Neel De/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning: package ‘Rcpp’ is in use and will not be installed
Installing 1 package: svd
Installing package into ‘C:/Users/Sagar Neel De/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/svd_0.4.1.zip'
Content type 'application/zip' length 510842 bytes (498 KB)
downloaded 498 KB

package ‘svd’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Sagar Neel De\AppData\Local\Temp\RtmpQvXgz5\downloaded_packages
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Sagar Neel De/AppData/Local/Temp/RtmpQvXgz5/devtoolsb44625b6420/jaredhuling-rESN-a88e873"  \
  --library="C:/Users/Sagar Neel De/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'rESN' ...
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'rESN'
* removing 'C:/Users/Sagar Neel De/Documents/R/win-library/3.5/rESN'
In R CMD INSTALL
Installation failed: Command failed (1)
> install.packages("Rtools")
Installing package into ‘C:/Users/Sagar Neel De/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.5.1)`

**Comment by jaredhuling** [comment]
It's not a bug, you need to download the latest version of Rtools

**Comment by ishonest** [comment]
Thanks Jared. It worked.
